### ISSUE TITLE
Don't create topics for remote datasets

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/streisand#26]
Remote datasets won't ever use a Kafka topic, so we shouldn't be creating them.

Acceptance criteria:
- [x] Don't create Kafka topics for remote datasets
- [x] Continue to create Kafka topics for batch/streaming datasets

**Comment by bbrewer-papa-x** [comment]
This was working as expected too. However, streisand only cares about streaming datasets, not batch, FYI
